version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - docker-dns
  docker-dns:
    image: finboxio/docker-dns
    restart: always
    ports:
      - 53:53/udp
  postgres:
    image: mdillon/postgis:9.6-alpine
    restart: always
    environment:
      VIRTUAL_HOST: postgres.docker
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated
  redis:
    image: redis:3-alpine
